services:
  tubeshelf:
    image: tubeshelf
    build: .
    container_name: tubeshelf
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    environment:
      BETTER_AUTH_SECRET: "replace-with-a-random-32+-char-secret"
    volumes:
      - ./data:/app/data
